config/routes.rb
BigosApp::Engine.routes.draw do
  devise_for :admin_users, {
      :class_name => "BigosApp::AdminUser",
      :module=> :devise,
      :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  }

  namespace :admin do
    resources :pages, :page_templates, :settings
    root :to=>"pages#index"
  end

  resources :pages
  root :to=>"pages#index"
  match '/:id' => 'pages#show', :via => 'get'
end

app/models/bigos_app/page_template.rb
module BigosApp
  class PageTemplate < ActiveRecord::Base
    attr_accessible :elements, :is_visible, :name, :position, :type
    has_many :pages

    validates :name, :presence => true

    def getPageElements page_id
      @elements = JSON.parse(self.elements) unless self.elements.blank?
      @elements.each do |element|
        element.last.to_i.times do
          page_element = eval(element.first).create(:page_id => page_id)
        end
      end unless @elements.blank?
    end
  end
end

app/controllers/bigos_app/admin/page_templates_controller.rb
require_dependency "bigos_app/admin/base_controller"

module BigosApp

  class Admin::PageTemplatesController < Admin::BaseController

    def new
      @page_template = BigosApp::PageTemplate.new
    end

    def edit
      @page_template = BigosApp::PageTemplate.find(params[:id])
      @elements = JSON.parse(@page_template.elements) unless @page_template.elements.blank?
    end

    def show
      @page_template = BigosApp::PageTemplate.find(params[:id])
      @elements = JSON.parse(@page_template.elements) unless @page_template.elements.blank?
    end

    def create
      @page_template = BigosApp::PageTemplate.new(params[:page_template])
      @page_template.elements = params[:elements].to_json

      if (@page_template.save)
        redirect_to action: :show, :id => @page_template.id
      else
        redirect_to action: :new
      end
    end

    def update
      @page_template = BigosApp::PageTemplate.find(params[:id])
      @page_template.elements = params[:elements].to_json
      if (@page_template.update_attributes(params[:page_template ]))
        redirect_to action: :show, :id => @page_template.id
      else
        redirect_to action: :edit, :id => @page_template.id
      end
    end

    def destroy
      @page_template = BigosApp::PageTemplate.find(params[:id])
      @page_template.destroy

      redirect_to admin_root_path
    end

  end

end

app/views/bigos_app/admin/page_templates/_form.html.erb
<%= simple_form_for [:admin,@page_template] do |f| %>
  <%= f.input :name %>
  <% BigosApp::PageElement.subclasses.each do |subclass| %>
    <%= label_tag eval(subclass).class_name %>
      <%= number_field_tag "elements[#{subclass}]", @elements.blank? ? nil : @elements[subclass], :in => 0...21, :class => "element" %>
    <% end %>
  <%= f.button :submit %>
<% end %>

app/views/bigos_app/admin/page_templates/edit.html.erb
<%= render :partial=>"form" %>

app/views/bigos_app/admin/page_templates/new.html.erb
<%= render :partial=>"form" %>

app/views/bigos_app/admin/page_templates/show.html.erb
<h2><%= @page_template.name  %></h2>

<ul>
  <% @elements.each do |element| %>
    <li><%= pluralize(element.last.to_i, eval(element.first).class_name) %></li>
  <% end unless @elements.blank? %>
</ul>
<%= link_to "Edit", edit_admin_page_template_path(@page_template) %>
<%= link_to 'Destroy', admin_page_template_path, method: :delete, data: { confirm: 'Are you sure?' } %>