config/routes.rb
BigosApp::Engine.routes.draw do
  devise_for :admin_users, {
      :class_name => "BigosApp::AdminUser",
      :module=> :devise,
      :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  }

  namespace :admin do
    resources :pages, :page_templates, :settings
    root :to=>"pages#index"
  end

  resources :pages
  root :to=>"pages#index"
  match '/:id' => 'pages#show', :via => 'get'
end

app/views/bigos_app/admin/pages/_form.html.erb
<%= simple_form_for [:admin,@page] do |f| %>
  <%= f.association:parent_page, :collection => @pages %>
  <%= f.input :template, :collection => @files %>
  <%= f.association :page_template %>
  <%= f.input :is_visible %>
  <%= f.input :label %>
  <%= f.input :name %>
  <%= f.input :position %>

  <ul class="accordion">
      <%= f.simple_fields_for :page_elements do |pe| %>
          <li>
            <div class="title">
              <h5>
                <%= pe.object.class.class_name %>
                <%= ": #{pe.object.name}" unless pe.object.name.blank? %>
              </h5>
            </div>
            <div class="content">
              <%= pe.input :position %>
              <%= render partial: pe.object.admin_render, locals: {pe:pe} unless pe.object.admin_render.blank? %>
            </div>
          </li>
      <% end %>
  </ul>

  <%= f.button :submit %>
<% end %>

app/views/bigos_app/admin/pages/_list.html.erb
<ul id="">
<%=
  content_tag_for(:li, @pages, :class => "page") do |item|
    page.label
  end
%>
</ul>

app/views/bigos_app/admin/pages/_table.html.erb
<%=
    collection_table(@pages, :id=>"pages-table") do |t|
        t.header :name
        t.header :type
        t.header :label
        t.header :position
        t.header :elements
        t.header :is_visible

        t.rows.alternate = :odd
        t.rows.each do |row, item, index|
            row.name
            row.type
            row.label
            row.position
            row.elements
            row.is_visible
        end
    end
%>

app/views/bigos_app/admin/pages/edit.html.erb
<%= render :partial=>"form" %>

app/views/bigos_app/admin/pages/show.html.erb
<h2><%= @page.name  %></h2>

<ul>
  <% @page.page_elements.each do |element| %>
    <li><%= element.class.class_name %></li>
  <% end %>
</ul>

<%= link_to "Edit", edit_admin_page_path(@page) %>
<% if current_admin_user.is_superadmin? %>
  <%= link_to 'Destroy', admin_page_path, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>