config/routes.rb
BigosApp::Engine.routes.draw do
  devise_for :admin_users, {
      :class_name => "BigosApp::AdminUser",
      :module=> :devise,
      :path_names => { :sign_in => 'login', :sign_out => 'logout'}
  }

  namespace :admin do
    resources :pages, :page_templates, :settings
    root :to=>"pages#index"
  end

  resources :pages
  root :to=>"pages#index"
  match '/:id' => 'pages#show', :via => 'get'
end

app/views/bigos_app/admin/layout/_menu.html.erb
<% if current_admin_user.is_superadmin? %>
  <%= link_to "Add  new page", new_admin_page_path, class: "secondary button" %>
<% end %>
<ul class="nav-bar vertical">
<% @pages.all.each do |page| %>
  <li class="<%= page.subpages.length > 0 ? 'has-flyout' : '' %>">
    <%= link_to page.name || page.label, admin_page_path(page) %>
    <% if page.subpages.length > 0  %>
        <%= link_to("#", :class=>"flyout-toggle") do %>
            <span></span>
        <% end %>
        <ul class="flyout">
            <% page.subpages.all.each do |page| %>
                <li>
                <%= link_to page.name || page.label, admin_page_path(page) %>
                </li>
            <% end %>
        </ul>
    <% end %>
  </li>
<% end %>
</ul>

app/views/bigos_app/admin/layout/_templates_menu.html.erb
<% if current_admin_user.is_superadmin? %>
    <%= link_to "Add new page template", new_admin_page_template_path, class: "secondary button" %>
    <ul class="nav-bar vertical">
        <% @page_templates.each do |page_template| %>
          <li>
            <%= link_to page_template.name, admin_page_template_path(page_template) %>
          </li>
        <% end %>
    </ul>
<% end %>